BellzStudio/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from BellzStudio import settings

from django.conf.urls.static import static # type: ignore

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("dev-stories/", include('stories.urls')),
    path("notes/", include('notes.urls')),

    # ---- API ROUTES ----
    path("api/accounts/", include('main.apiUrls')),
    path("api/notes/", include('notes.apiUrls')),

    
] + static(settings.STATIC_URL)
# + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

main/urls.py
from django.urls import path
from .views import *


app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path("about-us/", about, name="about-us"),
    path("contact/", contact, name="contact"),
    path("contact/<str:destination>/", contactType, name="contact_type"),


    # ----------- USER MANGEMENT   -------------
    path("profile/me", profile, name="profile"),
    path("profile/update", updateProfile, name="update-profile"),

    # ----------- USER AUTHENTICATION   -------------
    path("get-familiar", signUp, name="sign-up"),
    path("sign-in", signIn, name="sign-in"),
    path("sign-out", signOut, name="sign-out"),


    
    
]

notes/urls.py
from django.urls import path

from .api_v1_views import ApiV1Home



app_name = "notes"

urlpatterns = [
    # path("", index, name="index"),
    # path("write/", NewNote, name="write-note"),
    # # path("<uuid:noteID>/", Note, name="note"),
    # path("<str:date>/", NoteDate, name="notes-by-date"),
    # path("idea-tags/<uuid:id>/", IdeaNotes, name="notes-by-idea"),
    # path("new-idea/", NewIdea, name="new-idea"),
    # path("search/", Search, name="search"),
    # path("note/<str:slug>/", NoteView, name="note"),
    # path("d/<str:date>/", NoteDate, name="notes-by-date"),
    # path("idea-tags/<str:slug>/", IdeaNotes, name="notes-by-idea"),


    # # ----------- NOTE REACH    -------------
    # path("n/join-network/", networks, name="join-network"),
    # path("n/subscribe/", subscribe, name="subscribe"),
    # path("network/<int:level>/", network, name="network"),
    
    # ------ v1.API  ------
    path("v1", ApiV1Home.as_view(), name="api_home"),

]

notes/models.py
from django.db import models
import uuid
from django.utils.text import slugify

from main.models import User 
# Create your models here.


class IdeaTag(models.Model):
    slug = models.SlugField(max_length=40, primary_key=True, unique=True, blank=True)
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.name[0] != "#":
            self.name = f"#{self.name}"

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    

    def my_notes(self):
        return self.on_notes.all()

class NotePrivacy(models.Model):
    name = models.CharField(max_length=150, unique=True)
    level = models.IntegerField(unique=True)


    # ---- Network Info ----
    # color_code = models.CharField(max_length=20, null=True)


    class Meta:
        ordering = ('level',)

    def get_subscribers(self):
        try: 
            subs = Note.objects.filter(privacy_level=self)
            print(subs)
            print(self)
        except Exception as e:
            print(e)
            raise e
        
        return subs

    def __str__(self):
        return f"{self.level}: {self.name}"

class Note(models.Model):
    slug = models.SlugField(max_length=160, primary_key=True, unique=True, blank=True)
    title = models.CharField(max_length=150)
    text = models.TextField(null=False, blank=False)
    tags = models.ManyToManyField(IdeaTag, related_name='on_notes')
    privacy_level = models.ForeignKey(NotePrivacy, on_delete=models.SET_NULL, null=True, related_name="subGroup")
    written_at = models.DateTimeField(auto_now_add=True)


    

    class Meta: 
        ordering = ('-written_at', ) 

    def __str__(self): 
        return self.title 
    
def get_default_subscription_model():
    return NotePrivacy.objects.get(level='5').id

class Reader(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=False, related_name='reader_profile')

    subscription_level = models.ForeignKey(NotePrivacy, on_delete=models.SET_NULL, null=True, default=get_default_subscription_model )
    
    written_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    
    
    default =  {
        'id': "test-uuid",
        'user': {
                "id": "test-user-id-1",
                "email": "test-user-1"
        },
        'subscription_level': "test-uuid",
        'written-at': "test-uuid",
        'updated_at': "test-uuid",
        
    }

    class Meta: 
        ordering = ('-updated_at', ) 

    def __str__(self): 
        if self.user:
            return f"{self.user.email}" 
        else:
            return f"{self.default['user']['email']}" 

notes/forms.py
from django.forms import ModelForm

from .models import Note


class NoteForm(ModelForm):

    class Meta:
        model = Note
        fields = "__all__"

notes/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from datetime import timedelta, datetime
from datetime import date as realDate
import time
from django.urls import reverse
from requests import Response
from notes.serializers import IdeaTagSerializer
from notes.paginations import StandardResultsSetPagination
from notes.serializers import NoteSerializer
from django.contrib.auth.decorators import login_required
from notes.forms import NoteForm
from .models import Note, IdeaTag, NotePrivacy, Reader
# Create your views here.

from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer



def index(request):
    errors = {}
    print("Request user : ", request.user)
    user= request.user

    if not user.is_authenticated:
        user_first = ''
    else:
        if len(user.first_name) > 1:
            user_first = user.first_name[0]
        else:
            user_first = f"{user}"[0]
    # Date Selector
    week = []
    d = realDate.today()
    for x in range(-3, 4):
        week.append(d + timedelta(days=x))
    # Tags
    tags = IdeaTag.objects.all()
    try:
        tag_param = request.GET['tag']
        # print("Tag Param: ", request.GET['tag'])
    except Exception as e:
        tag_param = None
        # print("Error: ", e)
    
    if tag_param:
        try:
            tag_param = f"#{tag_param}"
            tag_param = IdeaTag.objects.get(name=tag_param)
        except Exception as e:
            print("No tag: ", e)
            tag_param = None
    
    
    # Fetch notes based n user's network
    # If request user is autheicted
    if not request.user.is_authenticated:
        notes = Note.objects.filter(privacy_level__level__gte=5)
        return render(request, 'notes/all-notes.html', {'week': week, 'notes': notes, 'tags': tags, 'errors': errors})


    # Get auth'd user reader profile
    try:
        reader_profile = Reader.objects.get(user=request.user)
    except Exception as e:
        # Couldn't get reader profile
        print(e)
        reader_profile = None
    if reader_profile == None:
        print(f"{request.user} is auth bu no reader profile assuming the" )
        if request.user.is_staff:
            notes = Note.objects.all()
        
    else:
        reader = reader_profile
        print("This Reader: ", reader)
        
        subscription = reader.subscription_level
        print("Subscription: ", subscription)
        print("Leve: ", subscription.level, "ID", subscription.id)

        notes = Note.objects.filter(privacy_level__level__gte=subscription.level)
        


    print("Notes: ", notes)

    print("Result length: ", len(notes))
    #errors['invalid_idea_format'] = "Invalid idea format"


class Notes(generics.RetrieveAPIView):
    """
    A view that returns a templated HTML representation of a given user.
    """
    queryset = Note.objects.all()
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, *args, **kwargs):
                # Date Selector
        week = []
        d = realDate.today()
        for x in range(-3, 4):
            week.append(d + timedelta(days=x))

        tags = IdeaTag.objects.all()
        posts = Note.objects.all()

        return Response({'week': week, 'notes': posts, 'tags': tags}, template_name='notes/all-notes.html')

    # return render(request, 'notes/all-notes.html', {'week': week, "user_first": user_first, 'notes': notes, 'tags': tags, 'errors': errors})

def NewNote(request):
    '''
    On GET: This view returns the entry form page on get
    On POST: calls the validate_entry(entry), if valid, calls parse_entry(entry) then save entry.

    '''
    if request.method == "POST":
        # Get authenticated user
        user = request.user


        # Get submited entry text
        print("Form: ", request.POST)
        d = dict(request.POST)
        print("Dict form: ", d)
        title = d['title'][0].title()
        print("Title: ", title)
        text = d['text'][0]
        print("Text: ", text)
        tags = d['tags']
        print("Tags: ", tags)
        privacy_level = d['privacy_level'][0]   # int(d['privacy_level'][0])+1
        print("Privacy Level: ", privacy_level)


        # # # Create new note instance
        try:
            pl = NotePrivacy.objects.get(level=privacy_level)
            new_note = Note.objects.create(title=title, text=text, privacy_level=pl)
            new_note.tags.set(tags)

        except Exception as e:
            print("Error: ", e)
            return HttpResponseRedirect(reverse("notes:index"))

        # # # Save new entry instance
        # new_note.save()

        # Redirect back home
        return HttpResponseRedirect(reverse("notes:index"))
    
    write_form_note = NoteForm()
    return render(request, 'notes/write.html', {'form': write_form_note})

def NewIdea(request):
    if request.method == "POST":

        idea_name = request.POST['idea_name']
        errors ={}
        errors['invalid_idea_format'] = "Invalid idea format"
        if len(idea_name) < 2:
            return HttpResponseRedirect(reverse("notes:index", 
                                                args=(), kwargs=()
                                        ))
        try:
            IdeaTag.objects.get_or_create(name=idea_name)
        except Exception as e:
            return HttpResponse("Error creating tag")


        return HttpResponseRedirect(reverse("notes:index"))

def NoteDate(request, date):
    print("Date: ", date)
    try:
        tag_param = request.GET['tag']
        print("Tag Param: ", request.GET['tag'])
    except Exception as e:
        tag = None
        print("Error: ", e)


    # Date Selector  content_params path
    week = []
    d = realDate.today()
    for x in range(-3, 4):
        week.append(d + timedelta(days=x))

    notes = Note.objects.filter(written_at__date=date)   
    notes_tags = list()
    # notes_tags = set(notes_tags)
    # notes_tags = list(notes_tags)

    if tag == None:
        for x in notes:
            for i in x.tags.values():
                notes_tags.append({
                                'id': dict(i)['id'],
                                'name': dict(i)['name']
                            })

    return render(request, 'notes/notes-date.html', 
                  {
                    'week': week, 
                    "day_notes": notes,
                    "tags": notes_tags
                })

def IdeaNotes(request, slug):
    try:
        idea = IdeaTag.objects.get(slug=slug)
    except:
        idea = IdeaTag.objects.none()
    

    # Get auth'd user reader profile
    try:
        reader_profile = Reader.objects.get(user=request.user)
    except Exception as e:
        # Couldn't get reader profile
        print(e)
        reader_profile = None
    if reader_profile == None:
        print(f"{request.user} is has no reader profile " )
        if request.user.is_staff:
            notes = Note.objects.all()
        else:
            idea_notes = idea.my_notes()
            notes = idea_notes.filter(privacy_level__level__gte=5)    
    else:
        reader = reader_profile
        print("This Reader: ", reader)
        
        subscription = reader.subscription_level
        print("Subscription: ", subscription)
        print("Level: ", subscription.level, "ID", subscription.id)
        idea_notes = idea.my_notes()
        notes = idea_notes.filter(privacy_level__level__gte=subscription.level )

    
    count = idea.my_notes().count()
    return render(request, 'notes/idea-notes.html', {'idea': idea, 'idea_notes': notes, 'idea_notes_count': count})

def NoteView(request, slug):
    try:
        note = Note.objects.get(slug=slug)
    except:
        note = None
    
    return render(request, "notes/note.html", {"note": note})

def Search(request):
    query = request.GET['query'].lower()
    print("Search Query: ", query)
    note_results = []
    notes = Note.objects.all()
    for note in notes:
        if query.lower() in note.text.lower():
            note_results.append(note)

    print(note_results)

    idea_results = []
    ideas = IdeaTag.objects.all()
    for idea in ideas:
        if query.lower() in idea.name.lower():
            idea_results.append(idea)

    print(idea_results)

    note_result_pks = [n.pk for n in note_results]

    note_results = Note.objects.filter(pk__in=note_result_pks) 

    # Get auth'd user reader profile
    try:
        reader_profile = Reader.objects.get(user=request.user)
    except Exception as e:
        # Couldn't get reader profile
        print(e)
        reader_profile = None
    if reader_profile == None:
        print(f"{request.user} is has no reader profile " )
        if request.user.is_staff:
            pass
        else:
            note_results = note_results.filter(privacy_level__level__gte=5)    
    else:
        reader = reader_profile
        print("This Reader: ", reader)
        
        subscription = reader.subscription_level
        print("Subscription: ", subscription)
        print("Level: ", subscription.level, "ID", subscription.id)
        note_results = note_results.filter(privacy_level__level__gte=subscription.level )
        
    return render(request, "notes/search.html", {

        "note_results": note_results,
        "idea_results": idea_results,
        "results_length": len(note_results) + len(idea_results)

        })

#    API ---------
class ApiV1Home(generics.ListAPIView):
    queryset = Note.objects.all().order_by("written_at")
    serializer_class = NoteSerializer
    permission_classes = []
    pagination_class = StandardResultsSetPagination
    search_fields = ['title']



def networks(request):

    networks = NotePrivacy.objects.all()
    
    return render(request, "notes/monitize/join-network.html", {"networks": networks})

def network(request, level):
    networks = NotePrivacy.objects.all()
    try:
        network = NotePrivacy.objects.get(level=level)

notes/templates/notes/all-notes.html
{% extends 'notes/index.html' %}

{% block head %}
                
    <title> Notes </title>
    
{% endblock %}


{% block notes %}
    <div id="notes-container" class="space-y-2 font-sans">
        {% for note in notes %}
            <div class="p-2 bg-opacity-30 animate-slideBtT bg-white border border-purple-100 rounded-md hover:scale-[101%] transition duration-300 shadow-sm shadow-purple-200">
                <div class="">
                    <div class="w-full flex justify-between items-center">
                        <a href="{% url 'notes:note' note.slug %} " >
                            <h1 class="font-bold text-gray-900 capitalize text-xl">
                                {{note.title}}
                            </h1>
                        </a>
                        <a href="{% url 'notes:network' note.privacy_level.level %} " >
                            <h1 class="font-bold text-purple-600 capitalize text-xs">
                                {{note.privacy_level.level}}.{{note.privacy_level.name}}
                            </h1>
                        </a>
                        
                    </div>
                    
                    
                    <p class="line-clamp-3 text-pretty text-sm md:text-md">
                        {{note.text}}
                    </p>

                    <span class="w-full flex justify-between items-center">
                        <p class="">
                            {% for tag in note.tags.values %}
                                <span 
                                    class="mx-1 rounded-full bg-purple-200 text-xs p-[2px] text-gray-600">
                                    {{tag.name}}
                                </span>
                            {% endfor %}
                        </p>
                        <p class="text-xs underline">
                            {{ note.written_at}}
                        </p>
                    </span>
                    

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

notes/templates/notes/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
        {% block head %}
                
    
        {% endblock %}
        
    </head>

    <body class="bg-slate-50">
        <div class="p-2 md:p-3 flex justify-between items-center space-y-3 border-b"> 
            <div class="">
                <span class="flex items-center ">
                    <a class="font-bold p-2" href="/">
                        <img src="{% static 'images/arrow-circle-left-black.svg' %}" alt="go back" class="w-7 h-7 hover:animate-swivvle" >
                    </a>
                    <h1 class="text-5xl text-purple-600 font-bold ">
                        <a href="/notes">Notes</a>
                    </h1>
                </span>
                

                <p> How I deal with my wandering thoughts</p>
            </div>

            <a href="{% url 'notes:write-note' %}" class="text-white relative bg-purple-600 p-2 rounded-md">
                 Write

            </a>
        </div>
    
        <div class="w-full space-y-1 py-2 md:py-4">
    
            <span class="w-full flex justify-center text-sm">
                <form class="w-4/5 md:w-1/2 relative border bg-white rounded p-1" method="GET" action="{% url 'notes:search' %}">
                    <input class="p-1 w-full border border-white rounded focus:border-purple-200  focus:ring-0 focus:outline-none" type="text" placeholder="Search notes and idea tags" name="query">
                    <input type="submit" value="Search" class="absolute right-1 top-1 bg-purple-700 p-1 text-white rounded border border-purple-500 hover:text-white hover:bg-purple-700">
                </form>
                
            </span>

        </div>

        <div class=" p-3 md:px-20">    
            {% block outlet %}
                
    
            {% endblock %}
        </div>

        
    </body>
</html>

notes/templates/notes/idea-notes.html
{% extends 'notes/base.html' %}


{% block head %}
    <meta description="{{idea.name}}" />
    <meta description="{{idea.description}}" />
    <title> Tag: {{idea.name}} </title>     
{% endblock %}



{% block outlet %}
<div id="notes-container" class="space-y-2 p-2 md:p-4">

    <h1 class="text-2xl md:text-3xl font-bold">
        {{idea.name}} ({{idea_notes_count}})
    </h1>
    <p class="text-sm md:text-md">
        {{idea.description}}
    </p>
    {% for note in idea_notes %}

    <div class="p-2 bg-opacity-30 animate-slideBtT bg-white border border-purple-100 rounded-md hover:scale-[101%] transition duration-300 shadow-sm shadow-purple-200">
        <div class="">
            <div class="w-full flex justify-between items-center">
                <a href="{% url 'notes:note' note.slug %} " >
                    <h1 class="font-bold text-gray-900 capitalize text-xl">
                        {{note.title}}
                    </h1>
                </a>
                <a href="{% url 'notes:network' note.privacy_level.level %} " >
                    <h1 class="font-bold text-purple-600 capitalize text-xs">
                        {{note.privacy_level.level}}.{{note.privacy_level.name}}
                    </h1>
                </a>
                
            </div>
            
            
            <p class="line-clamp-3 text-pretty text-sm md:text-md">
                {{note.text}}
            </p>

            <span class="w-full flex justify-between items-center">
                <p class="">
                    {% for tag in note.tags.values %}
                        <span 
                            class="mx-1 rounded-full bg-purple-200 text-xs p-[2px] text-gray-600">
                            {{tag.name}}
                        </span>
                    {% endfor %}
                </p>
                <p class="text-xs underline">
                    {{ note.written_at}}
                </p>
            </span>
            

        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

notes/templates/notes/index.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
        {% block head %}
                
    
        {% endblock %}
        
    </head>

    <body class="bg-slate-50 w-full">
        <div class="p-2 md:p-3 w-full flex justify-between items-center space-y-3 border-b"> 
            <div class="">
                <span class="flex items-center ">
                    <a class="font-bold p-2" href="/">
                        <img src="{% static 'images/arrow-circle-left-black.svg' %}" alt="go back" class="w-7 h-7 hover:animate-swivvle" >
                    </a>
                    <h1 class="text-5xl text-purple-600 font-bold ">
                        <a href="/notes">Notes</a>
                    </h1>
                </span>
                

                <p class="text-sm md:text-md"> How I deal with my wandering thoughts</p>
            </div>

            <div class="flex justify-center items-center space-x-1">
                {% if user.is_authenticated %}
                    <span class="rounded-full bg-purple-600 border-2 p-2 text-white"><a href="{% url 'main:profile' %}" class=" flex w-7 h-7 md:w-5 md:h-5 justify-center  items-center font-bold"> {{user_first}}</a></span>
                    {% else %}
                    <span class="rounded-md bg-white border-2 py-2 px-1 sm:p-2 text-xs sm:text-md text-gray-800"><a href="{% url 'notes:join-network' %}" class=" flex justify-center items-center font-medium"> Read my notes </a></span> 
                {% endif %}
                
                <a href="{% url 'notes:write-note' %}" class="text-white relative bg-purple-600 p-2 rounded-md">
                    Write
   
               </a>
            </div>

            
        </div>
    
        <div class="w-full space-y-1 py-1">
            <!-- <div 
                id="date-selector" 
                class=" text-gray-700 flex justify-center items-center space-x-1 md:space-x-5  p-1">
                
                    {% for day in week %}
                        <button class="text-xs md:text-sm lg:text-md border p-1 md:p-2 hover:font-bold focus:bg-purple-100 focus:font-bold rounded-md transition-colors ease-in-out ">
                            <a 
                                href="{% url 'notes:notes-by-date' day %}" 
                                class="transition-colors ease-in-out ">  
                                
                                {{day}} 
                            </a>
                        </button>
                    {% endfor %}
            </div> -->

            <div class="w-full flex flex-col space-y-1 items-center">
                <div 
                    id="tag-selector" 
                    class="w-full text-gray-700   flex flex-wrap gap-2 items-center justify-center md:gap-5 w-full">        
                        
                        {% for tag in tags %}
                            <a 
                                href="{% url 'notes:notes-by-idea' tag.slug %}" 
                                class="text-xs flex justify-center items-center md:text-sm lg:text-md border p-1 md:p-2 hover:font-bold hover:bg-purple-100  rounded-md transition-all ease-in-out ">  
                                
                                {{tag.name}} 
                            </a>
                            
                        {% endfor %}
                
                </div>
                {% if 'invalid_idea_format' in errors.keys %}
                    <p class="text-red-400 text-sm  animate-pulse"> {{errors.invalid_idea_format}}</p>
                {% endif %}

                <span class="text-sm">
                    <form method="POST" action="{% url 'notes:new-idea' %}">
                        {% csrf_token %}
                        <input class="p-1 focus:border  {% if 'invalid_idea_format' in errors.keys %} border border-red-500 {% endif%} rounded focus:border-purple-500  focus:ring-0 focus:outline-none" type="text" placeholder="New Idea Tag?" name="idea_name">
                        <input type="submit" value="Save Idea" class="bg-white p-1 text-gray-600 rounded border border-purple-500 hover:text-white hover:bg-purple-700">
                    </form>
                    
                </span>
                
            </div>

            <span class="w-full flex justify-center text-sm">
                <form class="w-4/5 md:w-1/2 relative border bg-white rounded p-1" method="GET" action="{% url 'notes:search' %}">
                    <input class="p-1 w-full border border-white rounded focus:border-purple-200  focus:ring-0 focus:outline-none" type="text" placeholder="Search notes and ideas" name="query">
                    <input type="submit" value="Search" class="absolute right-1 top-1 bg-purple-700 p-1 text-white rounded border border-purple-500 hover:text-white hover:bg-purple-700">
                </form>
                
            </span>

        </div>

        <div class=" p-3 md:px-20">    
            {% block notes %}
                
    
            {% endblock %}
        </div>

        
    </body>
</html>

notes/templates/notes/note.html
{% extends 'notes/base.html' %}


{% block head %}
    <title> Note: {{note.title}} </title>        
    
    {% for tag in note.tags.values %}
        <meta description="{{tag.name}}" />
    {% endfor %}   

{% endblock %}



{% block outlet %}
    <div id="note-container" class="space-y-2 font-sans">
        <div class="p-2 bg-opacity-20 md:px-10 animate-slideLtR bg-white  rounded-md duration-300">
                <h1 class="font-bold text-gray-900 capitalize text-3xl">
                    {{note.title}}
                </h1>

                <span class="w-full flex  justify-between items-center">
                    <p class="">
                        {% for tag in note.tags.values %}
                            <a href="{% url 'notes:notes-by-idea' tag.slug %}" 
                                class="mx-1 rounded-full bg-purple-200 text-xs p-[2px] text-gray-600">
                                {{tag.name}}
                            </a>
                        {% endfor %}
                    </p>
                    <p class="text-xs underline">
                        {{ note.written_at}}
                    </p>
                </span>
                
                <p class="mt-2 w-full text-justify leading-relaxed  selection:bg-purple-300 text-gray-800 font-serif font-normal text-lg">
                    {{note.text}}
                </p>

            </div>
    </div>
{% endblock %}

notes/templates/notes/notes-date.html
{% extends 'notes/index.html' %}







{% block notes %}
    <div id="notes-container" class="space-y-2">
        {% for note in day_notes %}

            <div class="p-2 bg-opacity-30 bg-white border border-purple-100 rounded-md hover:scale-[101%] transition duration-300 shadow-sm shadow-purple-200">
                <h1 class="font-bold text-gray-900 capitalize text-xl">
                    {{note.title}}
                </h1>
                
                <p class="line-clamp-3 text-pretty text-sm md:text-md">
                    {{note.text}}
                </p>

                <span class="w-full flex justify-between items-center">
                    <p class="">
                        {% for tag in note.tags.values %}
                            <span 
                                class="mx-1 rounded-full bg-purple-200 text-xs p-[2px] text-gray-600">
                                {{tag.name}}
                            </span>
                        {% endfor %}
                    </p>
                    <p class="text-xs underline">
                        {{ note.written_at}}
                    </p>
                </span>
                

            </div>
        {% endfor %}
    </div>
{% endblock %}

notes/templates/notes/write.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
    </head>

    <body class="">
        <div class="p-2 md:p-4 space-y-3 border-b bg-slate-50"> 
            <h1 class="text-5xl text-purple-600 font-bold">
                <a href="/notes">Notes</a>
            </h1>

            <p> How I deal with my wandering thoughts</p>
        </div>
    
        <div id="notes-canvas" class="space-y-2 p-2 md:p-4 bg-slate-50 h-screen ">

            <div class="flex flex-col items-center justify-center">

                <h1 class="text-2xl font-medium">
                    Write Note
                </h1>
                <p class="">
                    What's on your mind
                </p>
            </div>

            <form class="text-gray-800" action="{% url 'notes:write-note' %}" method="POST">
                {% csrf_token %}
                
                
                {% for field in form %}
                    <div class="flex flex-col items-start justify-center">
                        {{ field.label }}    
                        {{ field }}
                    </div>
                    
                {% endfor %}


                <input type="submit" class="w-1/2  hover:bg-purple-700 bg-purple-600 p-1 text-white cursor-pointer rounded" value="Post">
            </form>
        
        </div>



        
    </body>
</html>