BellzStudio/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from BellzStudio import settings

from django.conf.urls.static import static # type: ignore

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("dev-stories/", include('stories.urls')),
    path("notes/", include('notes.urls')),

    # ---- API ROUTES ----
    path("api/accounts/", include('main.apiUrls')),
    path("api/notes/", include('notes.apiUrls')),

    
] + static(settings.STATIC_URL)
# + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

main/urls.py
from django.urls import path
from .views import *


app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path("about-us/", about, name="about-us"),
    path("contact/", contact, name="contact"),
    path("contact/<str:destination>/", contactType, name="contact_type"),


    # ----------- USER MANGEMENT   -------------
    path("profile/me", profile, name="profile"),
    path("profile/update", updateProfile, name="update-profile"),

    # ----------- USER AUTHENTICATION   -------------
    path("get-familiar", signUp, name="sign-up"),
    path("sign-in", signIn, name="sign-in"),
    path("sign-out", signOut, name="sign-out"),


    
    
]

stories/urls.py
from django.urls import path
from .views import *

app_name = "stories"


urlpatterns = [
    path("", index, name="stories_index"),
    path("story/<uuid:id>", story, name="story"),

    # ------ DemoCraty ------
    path("dc/", DemoCratyIndex, name="dc_Index"),
    path("dc/home", DemoCratyDemo, name="dc_home"),
    path("dc/<uuid:id>", ElectionDetails, name="election_details"),
    path("dc/<uuid:id>/register", ElectionRegistration, name="election_registration"),
    path("dc/<uuid:id>/vote", VoteView, name="vote"),

]   

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

from main.manager import UserManager 
# Create your models here.



class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Personal Info
    email = models.EmailField(unique=True, null=False, blank=False)
    username = models.CharField(max_length=100, null=True, blank=True)
    
    # Verification
    is_verified = models.BooleanField(default=False)

    # DateTime
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        if self.is_superuser:
            self.is_verified = True
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.email



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,)
    image = models.ImageField(upload_to="media/users/images")

    def save(self, *args, **kwargs):
        self.id = self.user.id
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.user.email

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignUpForm(UserCreationForm):
    #email = forms.EmailField(max_length=120, help_text="Required. Type in your email")
    #Add additional fields to request for on sign up

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from notes.models import Reader
from .models import User
from django.contrib.auth import authenticate, login, logout
from main.forms import SignUpForm
# Create your views here.



def index(request):
    user = request.user
    
    try:
        user_profile = User.objects.get(email=user)
        print(user_profile.first_name)    
    except:
        user_profile = None
    
    return render(request, 'main/index.html', {'user': user_profile})


def about(request):

    return render(request, 'main/about-us.html', {})


def contact(request):

    destination = 'twitter'


    return HttpResponseRedirect(reverse(
                        "main:contact_type", args=(destination,)
                        ))
    # return render(request, "main/contact-us.html", {})


def contactType(request, destination):

    print(destination)

    contacts = {
        "twitter": {
            'link': 'https://twitter.com/imoctborn',
            'username': '@imoctborn',
            'icon_link': 'images/twit.png'               
        },
        "linkedin": {
            'link': 'https://linkedin.com/in/abeleje-olaniyi',
            'username': 'Abeleje Olaniyi',
            'icon_link': 'images/linkedin_pfp.jpeg'               
        },
        "email": {
            'link': 'mailto:olaniyigeorge77@gmail.com',
            'username': 'olaniyigeorge77@gmail.com',
            'icon_link': 'images/my-twitter.png'               
        },
    }

    info = contacts[destination]
    print(info)

    return render(request, "main/contact-des.html", {'destination': destination, 'info': contacts[destination]})


# USER MANGEMENT


def profile(request):
    user = request.user
    if not user.is_authenticated:
        user = None
        return render(request, 'main/my-profile.html', {"user": user})
        #user_profile = Profile.objects.get(user=user)
    
    return render(request, 'main/my-profile.html', {"user": user})

@login_required(login_url='/sign-in')
def updateProfile(request):
    user = request.user
    if not user.is_authenticated:
        user = None
        return render(request, 'main/my-profile.html', {"user": user})
    
    if request.method == "POST":
        print(request.POST)
        user = User.objects.get(id=user.id)
        print(user)
        if len(request.POST["first_name"]) > 0:
            user.first_name = str(request.POST["first_name"])
            print(request.POST["first_name"])
            user.save()
        if len(request.POST["last_name"]) > 0:
            user.last_name = str(request.POST["last_name"])
            print(request.POST["last_name"])
            user.save()
        user = User.objects.get(id=user.id)

        update = False
        return HttpResponseRedirect(reverse("main:profile"))
        #return render(request, 'main/my-profile.html', {"user": user, "update": update})
    
    update = True
    return render(request, 'main/my-profile.html', {"user": user, "update": update})


# NETWORK


def newtork(request):
    user = request.user
    if not user.is_authenticated:
        user = None
        return render(request, 'main/not.html', {"user": user})
        #user_profile = Profile.objects.get(user=user)
    
    return render(request, 'main/my-profile.html', {"user": user})


def signUp(request):

    try:
        role = request.GET['role']
        # print("Tag Param: ", request.GET['tag'])
    except Exception as e:
        role = None
        # print("Error: ", e)
    # role = request.GET['role'] or "" 

    print("Role: ", role)

    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']

        # Role
        reader = request.POST['reader'] or "off"
        print("Email:", email)
        print("Password:", password)
        print("Reader:", reader)


        if password != password_confirmation:
            print()
            return HttpResponseRedirect(reverse("main:sign-up"))    
        
        try:
            user, created = User.objects.get_or_create(email=email, password=password)
            print("User: ", user, created)
    
            #save user
            
            user.save()
            if reader == 'on':
                reader = Reader.objects.get_or_create(user=user)
                

        except Exception as e:
            print("Error during creation: ", e)
            return HttpResponseRedirect(reverse("main:sign-up"))
                
        try:

            # Get username and password for authentication
            email = request.POST['email']
            raw_password = request.POST['password']

            # Log user in with username and raw password
            print("User before auth: ", user)
            # user = authenticate(request, email=email, password=raw_password)
            
            if user:
                print("logging in...")
                login(request, user)
                print("Logged in")
                return HttpResponseRedirect(reverse("notes:index"))
        
            print("Couldn't log authencate user: ", user)
            return HttpResponseRedirect(reverse("main:index"))     
        except Exception as e:
            print("Error during auth/login: ", e)
            return HttpResponseRedirect(reverse("main:sign-up"))  
        #     return render(request, "main/signup.html", {
        # 'form': form,
        # 'message': 'Form not valid'
        # })
    else:
        form = SignUpForm()


    return render(request, 'main/sign-up.html', {"form": form})

def signIn(request):



    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        print("Email:", email)
        print("Password:", password)
        print("User before auth:", request.user)
        user = authenticate(request, email=email, password=password)
        print("User after auth:", user)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("notes:index"))
        else:
            print("User: ", user)
            return render(request, "main/sign-in.html", {
                'error': f"Error-{user}"
            })
    
    return render(request, "main/sign-in.html")

def signOut(request):
    user = request.user

    logout(request)
    
    return HttpResponseRedirect(reverse("notes:index"))

main/templates/main/about-us.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title> About Us: Bellz Studio</title>
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
    </head>

    <body class="bg-slate-50">
        <div class=" w-full relative">
            <div class="w-full p-2 flex top-0 items-center fixed z-20 bg-purple-700  font-medium">
                    <a href="/" class="pl-4 font-extrabold text-2xl text-white">Bellz</a>
                    <div id="header-nav"  class="flex flex-1 justify-center items-center">
                        <section id="mobile-menu" class="">

                        </section>
                        <section id="hr-nav" class="hidden text-white 500  space-x-5 ml-30 md:flex w-1/2 justify-between ">
                            <a 
                                href="/about-us" 
                                class="hover:underline transition-all  duration-1000"
                            > 
                                About 
                            </a>

                            <a 
                                href="/notes" 
                                class="hover:underline transition-all  duration-1000"
                            > 
                                Notes 
                            </a>

                            <a 
                                href="/dev-stories" 
                                class="hover:underline transition-all  duration-1000"
                            > 
                                Stories
                            </a>

                            <a 
                                href="/contact" 
                                class="hover:underline transition-all  duration-1000"
                            > 
                                Contact 
                            </a>
                        </section>
                    </div>    
            </div> 
            
            <div class="w-full p-4 mt-16  ">
                <div class="space-y-1">
                    <h2 class="font-extrabold w-full text-start  text-purple-600 text-5xl md:text-7xl">
                        About Us 
                    </h1>
                    <p class="italic "> Building micro services & products we believe should exist  </p>

                    <p 
                    class="mt-5"
                    > 
                        Bellz Studio was birthed from the idea that there is a lot of good that could be good that could be done from a small place when tech is applied to doing what it does best; making life easier. 
                    </p>
                </div>
                

                <div class=" space-y-1 mt-10 md:mt-0">
                    <h2 class="font-extrabold w-full text-start text-purple-600 text-5xl md:text-7xl">
                        Our Mission
                    </h1>
                    <p class="italic "> Building micro services & products we believe should exist  </p>

                    <p class="mt-5">
                        Our mission is to build solutions to as many problems as we can in our immediate locale and document the journey while at it. For now, that locale means Akure, Ondo State, Nigeria.
                    
                        We have a series of pain points we are working on which you can see <a href="{% url 'stories:dc_home' %}">here</a>
                        
                        We consider ourselves successful when we can get at least a thousand people to actually use this products to deal with the issues they address.
                    </p>
    
                </div>
            </div>          
    </div>
        
    </body>

</html>

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
        {% block head %}
                
    
        {% endblock %}
        
    </head>
    
    <body>
        {% block body %}
            
        {% endblock %}
    </body>

    
</html>

main/templates/main/contact-des.html
{% extends "main/contact-us.html" %}
{% load static %}

{% block contactType %}
<div class="w-full flex-col justify-center items-center p-3 ">
    <h1 class="text-3xl text-center font-bold w-full my-3 ">
        {% if destination == 'email' %}
            Send me an <span class="text-black">{{ destination }}</span>
        {% else %}
            Reach out to me on <span class="text-black">{{ destination }}</span>
        {% endif %}
    </h1>

    <div class="space-y-3 w-full transform duration-900">
        <a href="{{ info.link  }}" target="_blank" class="">
        
            <p class="flex p-2 underline items-center justify-center hover:italic text-center"> {{info.username}} </p>

            

            <div class=" w-full h-auto p-2">
                <img 
                src="/static/{{info.icon_link}}" 
                alt="{{destination}} page" 
                class="w-full h-[500px]"
                > 
            </div>
        </a>
    </div>
    
     
</div>
    
{% endblock %} 

main/templates/main/contact-us.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title> Contact: Bellz Studio</title>
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
    </head>

    <body >
        <div class="bg-slate-50 w-full flex flex-col  md:h-screen md:space-x-8 md:flex-row md:justify-between md:items-center px-2 md:px-40 space-y-2 md:space-y-0 h-screen">
            <div class="w-full p-4 md:w-1/2  space-y-3">
                <div class=" ">

                    <h2 class="font-extrabold text-purple-600 text-7xl">
                        <a href="/" class="w-full text-start ">Bellz Studio </a> 
                    </h1>
                </div>
                
                <p class="italic "> Building micro services & products we believe should exist  </p>

                <div class="w-full space-y-2 md:space-y-0 mt-10 md:flex justify-between items-center">
                

                    <a 
                        href="{% url 'main:contact_type'  'twitter' %}"
                        class="p-2 rounded-md bg-white md:hover:scale-110  transition ease-in-out flex justify-center px-5 hover:bg-purple-600 hover:text-white hover:font-bold  border w-auto font-bold"
                    > 
                        Twitter 
                    </a>
                    <a 
                        href="{% url 'main:contact_type'  'linkedin' %}"
                        class="p-2 rounded-md bg-white md:hover:scale-110  transition ease-in-out flex justify-center px-5 hover:bg-purple-600 hover:text-white hover:font-bold  border w-auto font-bold"
                    > 
                        LinkedIn 
                    </a>
                    <a 
                        href="{% url 'main:contact_type'  'email' %}"
                        class="p-2 rounded-md bg-white md:hover:scale-110  transition ease-in-out flex justify-center px-5 hover:bg-purple-600 hover:text-white hover:font-bold  border w-auto font-bold"
                    > 
                        Email 
                    </a>
                </div>
            </div>    
            
            <div class="w-full md:w-1/2 transform duration-500   bg-purple-700 text-white h-full flex items-center justify-center">
                {% block contactType %}

                {% endblock %}
            </div>
        </div>

    </body>

</html>

main/templates/main/my-profile.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
        <title> BellzStudio </title>
    </head>

    <body class="relative w-full h-full">
        
        <div class="bg-slate-50 text-gray-800  w-full md:h-screen   flex flex-col md:space-x-4 lg:space-x-8 md:flex-row md:justify-between md:items-center px-2 md:px-20 lg:px-40 space-y-2 md:space-y-0 ">
            
            <div class="w-full  p-4 md:w-1/2 mt-8 md:mt-0 space-y-3">
                <div class="mt-4">
                    <h1 
                        class="font-bold text-gray-700 text-xl md:text-3xl"
                        >
                        {% if user.first_name %}
                            Hi <span class="text-purple-700"> {{user.first_name}}</span>! Welcome to
                        {% else %}
                            Hi there! This is
                        {% endif %} 
                    </h1>
                    <h2 class="font-extrabold text-purple-600 text-7xl">
                        <p class="w-full text-start ">About Me </p> 
                    </h1>
                </div>
                
                <form action="{% url 'main:update-profile' %}" method="post" class="w-full space-y-2">
                    {% csrf_token %}
                    <div class="flex flex-col">
                        <p>Firstname</p>
                        {% if update %}
                            <input type="text" name="first_name" placeholder="{{user.first_name}}" class="ring-0 border-0 outline-none p-2 ring-0 rounded-md bg-white font-medium text-lg text-purple-600">
                        {% else %}
                            <p class="p-2  rounded-md bg-white font-medium text-lg text-purple-600">{{user.first_name}}</p>
                        {% endif %}
                        
                    </div>

                    <div class="flex flex-col">
                        <p>Lastname</p>
                        {% if update %}
                            <input type="text" name="last_name" placeholder="{{user.last_name}}" class="ring-0 border-0 outline-none p-2 ring-0 p-2 ring-0 rounded-md bg-white font-medium text-lg text-purple-600">
                        {% else %}
                            <p class="p-2 rounded-md bg-white font-medium text-lg text-purple-600">{{user.last_name}}</p>
                        {% endif %}
                    </div>

                    <div class="flex flex-col">
                        <p>Email</p>
                        <p class="p-2 rounded-md bg-white font-medium text-lg text-purple-600">{{user.email}}</p>
                    </div>

                    {% if user.reader_profile %}
                        <div class="flex flex-col">
                            <span class="w-full flex justify-between items-center ">
                                <p>Subscription Level</p> 
                                <a href="{% url 'notes:join-network' %}" class="italic text-purple-600 underline text-sm"> Know me better </a>
                            </span>
                            <p class="p-2 rounded-md bg-white font-medium text-lg text-purple-600">{{user.reader_profile.subscription_level}}</p>
                        </div>
                    {% endif %}


                    {% if update %}
                        <div class="w-full flex justify-end ">
                            <input type="submit" value="Update" class="p-2 border rounded-md bg-green-600 text-white cursor-pointer"> 
                        </div>
                        {% else %}
                        <div class="w-full flex">
                            <div class="w-full flex  ">
                                <a href="{% url 'main:update-profile' %}" class="p-2 border rounded-md font-medium text-gray-800"> Update </a>
                            </div>
                            <div class="w-full flex justify-end ">
                                <a href="{% url 'main:sign-out' %}" class="p-2 border rounded-md bg-red-500 text-white"> Log out</a>
                            </div>
                        </div>
                    {% endif %}
                    

                </form>
            
            </div>    
            
            <div class="w-full  md:flex-1 mb-5 md:mb-0 flex justify-center">
                <a 
                    href="/" 
                    class="text-5xl  animate-slideBtT md:animate-[slideRtL_1.5s_ease-in-out] font-bold w-full flex justify-center h-auto"
                > 
                
                    <img src="{% static 'images/memoji.png' %}" class="  border-4 border-purple-600 w-full h-auto rounded-full"/>

                </a>
                
            </div>
            
            
        </div>
        <img src="{% static 'images/curlyVectorTop.svg' %}" alt="curlyV" class="absolute top-0 left-0 "/>
        <img src="{% static 'images/curlyVectorBottom.svg' %}" alt="curlV" class=" absolute  -bottom-16 md:-bottom-1 right-0 "/>
        <a href="/" class="absolute  top-2 left-2 text-white text-sm space-x-2 flex items-center "> 
            <img src="{% static 'images/arrow-circle-left-white.svg' %}" alt="go back" class="w-7 h-7 text-white hover:animate-swivvle" >
            <p> Go home </p>
        </a>
    </body>

</html>

main/templates/main/sign-in.html
{% extends 'main/base.html' %}

{% block head %}
    <title> Sign In</title>
{% endblock %}



{% block message %}
    
{% endblock %}


{% block body %}
    <div class="w-full h-screen space-y-2 flex flex-col text-white bg-gray-950 w-full flex justify-center items-center">
        <div class="w-1/2 mb-5 text-5xl text-purple-600 flex items-center justify-center font-bold px-5">
            Sign In!
        </div>

        <div class="">
            <div class="">
                {% if message %}
                    <div class="w-full py-5 text-white font-bold animate-pulse border-2 border-red-600 flex justify-center items-center"> 
                        {{ message }}
                    </div>
                {% endif %}

                {% if error %}
                    <div class="w-full py-2 text-red-500 font-bold animate-pulse border-2 border-red-600 flex justify-center items-center"> 
                        {{ error }}
                    </div>
                {% endif %}
            </div>
            

            <form action="{% url 'main:sign-in' %}" method="post" class="w-full flex flex-col items-center">
                    {% csrf_token %}
                    
                    <div class="w-full">
                        <label class=""> Email</label>
                        <input type="text" name="email" class="rounded p-2 text-gray-900 w-full "  placeholder="Email">  </input>
                    </div>
                    <div class="w-full">
                        <label class=""> Password </label>
                        <input type="password" name="password" class="rounded p-2 text-gray-900 w-full "  placeholder="Password"> </input>
                    </div>
                    <input 
                        type="submit"  
                        class="rounded-md  cursor-pointer hover:bg-purple-700 hover:bg-purple-600 flex justify-center items-center bg-purple-600 my-4 p-2 w-full" 
                        value="Sign In"
                    >
            </form>

            <a href="{% url 'main:sign-up' %}" class="w-full flex text-sm hover:font-medium hover:text-md underline justify-center"> Sign Up </span>

        
        </div>

        
    </div>
{% endblock %}

main/templates/main/sign-up.html
{% extends 'main/base.html' %}

{% block head %}
    <title> Sign Up</title>
{% endblock %}



{% block message %}
    
{% endblock %}


{% block body %}
    <div class="w-full h-screen flex flex-col text-white bg-gray-950 w-full flex justify-center items-center">
        <div class="w-1/2 text-5xl text-purple-600 flex items-center justify-center font-bold px-5">
            Join Us!
        </div>

        <div class="">
            {% if message %}
                <div class="w-full py-5 text-white font-bold bg-red-600 flex justify-center items-center"> 
                    {{ message }}
                </div>
            {% endif %}

            <form action="{% url 'main:sign-up' %}" method="post" class="w-full flex flex-col space-y-2 items-center">
                    {% csrf_token %}
                    
        
                    <div class="w-full">
                        <label class=""> Email</label>
                        <input type="text" name="email" class="rounded p-2 text-gray-900 w-full "  placeholder="Email"> {{ field }} </input>
                    </div>
                    <div class="w-full">
                        <label class=""> Password </label>
                        <input type="text" name="password" class="rounded p-2 text-gray-900 w-full "  placeholder="Password"> {{ field }} </input>
                    </div>
                    <div class="w-full">
                        <label class=""> Confirm Password </label>
                        <input type="text" name="password_confirmation" class="rounded p-2 text-gray-900 w-full " placeholder="Confirm Password">  </input>
                    </div>

                    <div class="w-full flex justify-between">
                        <label class=""> Reader? </label>
                        <input type="radio" name="reader" class="p-1" > 
                    </div>
                    
                    <input 
                        type="submit"  
                        class="rounded-md cursor-pointer hover:bg-purple-700 hover:bg-purple-600 flex justify-center items-center bg-purple-600 my-4 p-2 w-full" value="Sign Up">
                </form>

                <a href="{% url 'main:sign-in' %}" class="w-full py-2 flex text-sm hover:font-medium hover:text-md underline justify-center"> Sign In </span>

        
        </div>

        
    </div>
{% endblock %}