BellzStudio/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from BellzStudio import settings

from django.conf.urls.static import static # type: ignore

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("dev-stories/", include('stories.urls')),
    path("notes/", include('notes.urls')),

    # ---- API ROUTES ----
    path("api/accounts/", include('main.apiUrls')),
    path("api/notes/", include('notes.apiUrls')),

    
] + static(settings.STATIC_URL)
# + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

main/urls.py
from django.urls import path
from .views import *


app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path("about-us/", about, name="about-us"),
    path("contact/", contact, name="contact"),
    path("contact/<str:destination>/", contactType, name="contact_type"),


    # ----------- USER MANGEMENT   -------------
    path("profile/me", profile, name="profile"),
    path("profile/update", updateProfile, name="update-profile"),

    # ----------- USER AUTHENTICATION   -------------
    path("get-familiar", signUp, name="sign-up"),
    path("sign-in", signIn, name="sign-in"),
    path("sign-out", signOut, name="sign-out"),


    
    
]

stories/urls.py
from django.urls import path
from .views import *

app_name = "stories"


urlpatterns = [
    path("", index, name="stories_index"),
    path("story/<uuid:id>", story, name="story"),

    # ------ DemoCraty ------
    path("dc/", DemoCratyIndex, name="dc_Index"),
    path("dc/home", DemoCratyDemo, name="dc_home"),
    path("dc/<uuid:id>", ElectionDetails, name="election_details"),
    path("dc/<uuid:id>/register", ElectionRegistration, name="election_registration"),
    path("dc/<uuid:id>/vote", VoteView, name="vote"),

]   

stories/models.py
from django.db import models
import datetime
from django.urls import reverse 
from django.utils import timezone
import uuid
from main.models import User

#  ------------ Story ------------

class Story(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4())
    content = models.FileField(upload_to="static/story", null=True, blank=True)

    child = models.OneToOneField('self', null=True, blank=True, on_delete=models.SET_NULL)

#  ------------ DemoCraty ------------

class Voter(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    person = models.OneToOneField(User, on_delete=models.CASCADE, related_name='voter_identity')

    def __str__(self):
        return f"{self.person.email}"
    

    def save(self, *args, **kwargs):
        self.id = self.person.id
        super().save(*args, **kwargs)

class Party(models.Model):
    name = models.CharField(max_length=200)
    acronym = models.CharField(max_length=10, default="PARTY")
    ideology = models.CharField(max_length=550)

    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.acronym}"

class Election(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150)
    date = models.DateField()
    parties = models.ManyToManyField(Party, blank=True, related_name='elections_participated_in')
    registered_voters = models.ManyToManyField(Voter, blank=True, related_name='election_registrations')

    def registered_voters_no(self):

        return self.registered_voters.count()
    

    def get_absolute_url(self):
        return reverse("stories:election_details", kwargs={"id": self.id})
    # def conduct_election(self):
    #     if self.validate_election_date():
    #         self.register_voters()
    #     else:
    #         print("Election date is not valid.")

    # def validate_election_date(self):
    #     current_date = timezone.now().date()
    #     if self.date < (current_date - timedelta(weeks=2)):
    #         return True
    #     else:
    #         return False

    # def register_voters(self):
    #     for party in self.parties.all():
    #         for voter in party.voters.all():
    #             if voter.registered:
    #                 self.voting_results.add(voter)
    #             else:
    #                 print(f"{voter.name} is not registered to vote in {self.name}.")

    def vote(self, voter, party):
        if party in self.parties.all() and voter.registered:
            if voter not in self.voting_results.all():
                self.voting_results.add(voter)
                voter.vote(self, party)
            else:
                print(f"{voter.name} has already voted in {self.name}.")
        else:
            print(f"{voter.name} is not eligible to vote in {self.name}.")

    def __str__(self):
        return self.name

class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    voter = models.ForeignKey(Voter, on_delete=models.CASCADE, related_name='voter_votes')
    election = models.ForeignKey(Election, on_delete=models.CASCADE, related_name='election_votes')
    party = models.ForeignKey(Party, on_delete=models.CASCADE, related_name='party_votes')


    time_casted = models.DateTimeField(auto_now_add=True)

stories/views.py
import os
import uu
from django.http import HttpResponseRedirect
from django.shortcuts import render
import datetime
import markdown

from BellzStudio.settings import BASE_DIR

from django.urls import reverse
from .inspo import demo_craty_inspirations
from .models import Election, Party, Story, Voter, Vote
from notes.models import IdeaTag


from django.core.files.storage import default_storage

def index(request):
    user = request.user

    stories = Story.objects.all()
    return render(
                    request, 
                    "stories/dev-stories.html", 
                    {
                        "user": user, 
                        "stories": stories
                    }
                )

def story(request, id):
    print("Story id: ", id)
    story = Story.objects.get(id=id)
    print(story)
    mdentry =  story.content.url #util.get_entry(title)
    
    try:
        # f = f"{BASE_DIR}{story.content.url}"

        f = default_storage.open(f"{BASE_DIR}{story.content.url}")
        print("F: ", f)
        #f = default_storage.open(story.content.url)
        c = f.read().decode("utf-8")
        md = markdown.Markdown(extensions=["fenced_code"])
        cc=  markdown.markdown(c)
        cc = md.convert(story.content)
        print("CC: ", cc)
        print("C: ", c)
    except Exception as e:
        print("File not found: ", e)
    
    print(f"Content: ", mdentry)
    converted_content = markdown.markdown(mdentry)
    print(f"Converted entry: ", c)
    return render(request, "stories/story.html", {"story": story, "content": cc})


def DemoCratyIndex(request):
    inspo = demo_craty_inspirations
    democraty_idea = IdeaTag.objects.get(name="#DemoCraty")
    return render(request, "stories/dc_index.html", {'insp': inspo, "DemoCraty": democraty_idea})

def DemoCratyDemo(request):
    elections = Election.objects.all()

    return render(request, "stories/dc_home.html", {'elections': elections})

def ElectionDetails(request, id):
    user = request.user
    message = ""
    reg= False
    voted = False

    try:
        election = Election.objects.get(id=id)
    except:
        election = Election.objects.none()

    election_date = datetime.datetime.strptime("2024-04-24", "%Y-%m-%d").date()
    now = datetime.date.today()

    print("Now: ", now)
    print("Election date: ", election.date)

    print()
    print("Diff: ", (election.date - now).days)
    if user.is_authenticated:
        try:
            voter, created = Voter.objects.get_or_create(person=user)
            reg = voter.election_registrations.filter(pk=election.id).exists()
            print("Reg: ", reg)
        except Exception as e:
            print("Exception: ", e)
            voter = None
            message = "This user can't be a voter"
    else:
        voter = None
        message = "You have to sign in to participate in the electoral processes"

    print("Voter: ",  voter)
    # Check if user has registered for this election
    try:
        pass # print("Reg:", reg)
    except:
        pass

    
    # Check if user has voted
    if voter:
        try:
            voted = Vote.objects.filter(voter=voter, election=election).exists()
            print("This user has voted: ", voted)
        except Exception as e:
            print("Voted Exception: ", e)
            voted = False

    # Get votes in this election
    results = {}    
    votes = Vote.objects.filter(election=id).count
    for party in election.parties.values():
        results[f"{party['name']}_result"] = Vote.objects.filter(election=id, party=party['id']).count

    return render(request, "stories/election_details.html", 
                    {
                    'election': election, 
                    'time_diff': (election.date - now).days,
                    'user': request.user,
                    'voter': voter,
                    'message': message,
                    "vote": True,
                    'user_is_registered': reg, 
                    "voted": voted,
                    "votes": votes,
                    "results": results

                } 
                )

def ElectionRegistration(request, id):
    
    if request.method == "POST":
        voter_id = request.POST['voter']
        
        try: 
            voter = Voter.objects.get(id=voter_id)
            election = Election.objects.get(id=id)
        except Exception as e:
            print("Error: ", e)

        # Add user to registered voters --- Redirect to reg page if more actions need to be done
        try:
            election.registered_voters.add(voter_id)
        except Exception as e:
            print("Registration error: ", e)

        return HttpResponseRedirect(
                reverse(
                        "stories:election_details",args=(id,)
                        )
        )


    else:
        return HttpResponseRedirect(
                reverse(
                        "stories:election_details",args=(id,)
                        )
        )


def VoteView(request, id):
    if request.method == "POST":
        try:
            selected_party = request.POST['party_choice']
        except:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse(
                        "stories:election_details",args=(id,)
                        )))
        print("User: ", request.user)
        try:
            voter = Voter.objects.get(person=request.user)
        except Exception as e:
            print("Error: ", e)
            return HttpResponseRedirect(
                reverse(
                        "stories:election_details",args=(id,)
                        )
        )
        party = Party.objects.get(id=selected_party)
        election = Election.objects.get(pk=id)
        print("Voter: ", voter)
        print("Selected Party ID: ", selected_party)
        print("choice_id: ", party)
        print("Election id: ", election)

        # Create Vote instance with VOTER, PARTY AND ELECTION attrs
        v= Vote(voter=voter, party=party, election=election)
        v.save()
        return HttpResponseRedirect(
                reverse(
                        "stories:election_details",args=(id,)
                        )
        )
    
    else:
        return HttpResponseRedirect(
                reverse(
                        "stories:election_details",args=(id,)
                        )
        )

stories/templates/stories/dc_home.html
{% extends "stories/democraty.html" %}

{% load static %}

{% block title %}
    <title> Elections</title>
{% endblock %}

{% block body %}
    <h1 class="p-6 text-5xl">
        Elections
    </h1>

    <hr>

    <div class="p-4 md:flex justify-between items-center ">
        <span class="flex "> There are <p class="font-bold px-1"> {{elections | length }} </p> elections scheduled </span>
        <a href="/"> Get started</a>
    </div>
    
    <div class="p-1 md:p-4">
        <ul>
            {% for x in elections %}
                <a href="{{x.id}}">
                    <li class="font-medium bg-purple-50 p-1  rounded">
                        -> {{ x }}
                    </li> 
                </a>   
            {% endfor %}    
        </ul>

    </div>

    {% block details %}
        
    {% endblock %}


{% endblock %}

stories/templates/stories/dc_index.html
{% extends "stories/democraty.html" %}

{% load static %}

{% block title %}
    <title> DemoCraty</title>
{% endblock %}

{% block body %}

    <div class="w-full flex border-b justify-between gap-2 items-center p-4 ">
        <div class="w-2/3 md:w-1/2 flex flex-col">
            
            <h1 class="text-3xl md:text-5xl text-purple-600 font-extrabold">
                <a href="/">DemoCraty</a>
            </h1>
    
    
            <p class="md:mt-5 text-sm md:text-md">
                A proposed solution to the inadequacies of the democratic and electoral process of Nigeria 
            </p>
        </div>
    
        <a href="{% url 'stories:dc_home' %}"class="flex-col justify-center items-center  hover:text-white hover:bg-purple-700 transition ease-in-out md:1/2 bg-purple-100 rounded-md shadow p-2 flex ">
            
                <img 
                    src="{% static 'images/vote.png' %}" 
                    class="w-[60px]  md:w-[100px] lg:w-[120px] rounded-full h-auto"
                >
            
                <p class="italic text-xs">
                     Click icon to try 
                </p>
        </a>
        
        
        
    </div>
    <a 
        href="{% url 'notes:notes-by-idea' DemoCraty.slug %}"
        class="w-full flex text-xl   mt-4 justify-center items-center font-medium underline "
    >

        <h1 class=""> Notes on my understanding of the oppotunity(problem)</h1>
    </a>

    <p 
        class="w-full flex text-xl py-6 mt-4 justify-center items-center font-bold">
        What are people saying about this opportunity? 
    </p>


    <div class="w-full px-4 grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 grid-flow-row gap-3 text-sm text-gray-900">
        
        {% for x in insp %}
         {{ x | safe }}
        {% endfor %}
    </div>



    <!-- <div id="demo-notes" class="h-screen w-full animate-slideBtT bg-red-200">

    </div> -->





{% endblock %}

stories/templates/stories/democraty.html
{% load static %}

<!DOCTYPE html>

<html lang='en'>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'styles/output.css' %}" />

        {% block title %}

        {% endblock%}

        {% block scripts %}

        {% endblock%}
    </head>

    <body class="">
        
        {% block body %}
        
        {% endblock%}

    </body>
</html>

stories/templates/stories/dev-stories.html
{% extends 'stories/index.html' %}



{% block head %}
    <title> Stories </title>        
    
{% endblock %}




{% block stories %}
    <div id="stories-container" class="space-y-2 font-sans">
        {% for story in stories %}
            <div class="p-2 bg-opacity-30 animate-slideBtT bg-white border border-purple-100 rounded-md hover:scale-[101%] transition duration-300 shadow-sm shadow-purple-200">
                <div class="">
                    <div class="w-full flex justify-between items-center">
                        <a href="{% url 'stories:story' story.id %} " >
                            <h1 class="font-bold text-gray-900 capitalize text-xl">
                                {{story.id}}
                            </h1>
                        </a>
                    </div>
                    
                    <p class="line-clamp-3 text-pretty text-sm md:text-md">
                        {{story.content}}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

stories/templates/stories/election_base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">

        <title>
            {% block title %}

            {% endblock %}
        </title>
        

        {% block scripts %}

        {% endblock %}


    </head>

    <body>

        {% block content %}

        {% endblock %}

    </body>
</html>

stories/templates/stories/election_details.html
{% extends "stories/election_base.html" %}
{% load static %}


{% block title %}
    DemoCraty: {{ election.name }} 
{% endblock %}


{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js" defer></script>
<script src="{% static 'js/track_election.js' %}" defer></script>
{% endblock %}


{% block content %}
    <div class="p-8 md:p-20 flex justify-center items-center  w-full h-screen">

        <div class="w-full h-full flex flex-col bg-purple-50 items-ceter  p-4 rounded-md md:rounded-lg ">
                
            <h1 class="text-3xl text-center md:text-5xl font-bold p-3 w-full flex justify-center">
                <a href="/"> {{ election.name }}</a>
            </h1>
            <h2 class="text-center p-1 space-x-2 w-full flex justify-center">
                <p> Scheduled for:</p> <p class="font-medium "> {{ election.date }}</p>
            </h2>
            
            <div class="md:flex flex-reverse gap-2">
                <div class="border rounded h-full w-full md:w-1/2">
                    
                        <p class="flex text-center justify-center">{{ election.parties.count }} parties have registered for this election</p>
                        <span class="flex justify-around items-center">
                            {% for party in election.parties.all %}
                                <span class="hover:bg-purple-700 hover:text-white flex p-2 border bg-white rounded-md justify-center items-center space-x-3">
                                    <p class="font-medium">{{party.name}}</p>
                                </span>
                            {% endfor %}
                        </span>

                        <p class="flex text-center justify-center"> Number of registered voters {{ election.registered_voters.count }}</p> 
                        {% if time_diff > 0 %}
                                <p class="flex text-center justify-center">Voting will commence in {{ time_diff }} days.</p> 
                            {% else %}
                                <p class="flex text-center justify-center text-red-500 font-bold underline">This election closed {{ time_diff }} days ago.</p>
                        {% endif %}
                    
                
                    <div id="notis" class="">
                        {% if not voter %}
                            <a href="/" class="text-red-500 ">{{ message }}</a>
                        {% endif %}

                        {% if voted == True %}
                            <p class="flex text-center justify-center text-blue-500" > You have voted in this election </p>
                        {% else %}

                        {% endif %}


                        {% if user_is_registered == False  and not voted %}
                            <form action="{% url 'stories:election_registration' election.id %}" class="w-full flex flex-col" method="post">
                                {% csrf_token %}

                                <input type="type" hidden name="voter" value="{{ user.id }}" />
                                
                                <span class="flex space-x-3 items-center">
                                    <p class="text-red-500"> You haven't registered for this election</p>
                                    <input type="submit" class="p-1 hover:bg-purple-800 text-white font-medium bg-purple-700 border rounded-md" value="Register"/>
                                </span>
                            </form>
                            
                        {% endif %}

                    </div>

                    {% if not voted and user_is_registered  %}
                        <form action="{% url 'stories:vote' election.id %}" class="w-full flex flex-col" method="post">
                            {% csrf_token %}
        
                            {% for party in election.parties.all %}
                                <span class="flex justify-center items-center space-x-3">
                                    <label class="">
                                        {{party.name}}
                                    </label>
        
                                    <input type="radio" name="party_choice" value="{{ party.id }}" />
                                </span>
                            {% endfor %}
                            <input type="submit" class="p-2 hover:bg-purple-800 text-white font-medium bg-purple-700 border rounded-md" value="Vote"/>
        
                        </form>
                    {% endif %}
                </div>

                <div id='results' class="border rounded w-full md:w-1/2 p-2">
                    <span class="flex text-5xl p-2 space-x-2  w-full justify-center items-center">
                        <p class="font-bold"> {{ votes }} </p> 
                        <p class="text-gray-800"> votes</p>
                    </span>

                    <span class="w-full space-y-2">
                        {% for party in election.parties.all %}
                            <span class="flex p-2 border bg-white rounded-md justify-center items-center space-x-3">
                                <p class="font-bold text-2xl">{{results | length}}</p>
                                <p class="flex ">{{party.name}}</p>
                                
                            </span>
                            
                        {% endfor %}
                        {% for r in results %}
                            {{r}}
                        {% endfor %}
                    </span>

                </div>
            </div>
        


        </div>
    
    </div>
{% endblock %}

stories/templates/stories/index.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
        {% block head %}
                
    
        {% endblock %}
        
    </head>

        <body class="bg-slate-50 w-full">
            <div class="p-2 md:p-3 w-full flex justify-between items-center space-y-3 border-b"> 
                <div class="w-full space-x-2 flex flex-col justify-start">
                    <span class="flex items-center">
                        <a class="font-bold " href="/">
                            <img src="{% static 'images/arrow-circle-left-black.svg' %}" alt="go back" class="w-7 h-7 hover:animate-swivvle" >
                        </a>
                        <div class="">   
                            <h1 ><a href="{% url 'stories:stories_index' %}" class="text-3xl text-purple-600 font-bold ">Developer Stories</a> </h1>
                            <p class="text-sm md:text-md">BTS of our products</p>
                        </div> 
                    </span>
                    

                    
                </div>



                
            </div>


        <div class=" p-3 md:px-20">    
            {% block stories %}
                
    
            {% endblock %}
        </div>

        
    </body>
</html>

stories/templates/stories/story.html
{% extends "stories/index.html" %}

{% load static %}

{% block head %}
    <title> DemoCraty</title>
    <link rel="stylesheet" href="{% static 'styles/output.css' %}">
{% endblock %}

{% block stories %}

    <div class="w-full p-2 rounded border">
        <div class=" flex flex-col">
            
    
            <p class="text-purple-600 font-extrabold">
                {{ story.id }}
            </p>
        </div>

        <div class="w-full">
            
            {{ content | safe  }}

        </div>
    
        
    </div>



    <!-- <div id="demo-notes" class="h-screen w-full animate-slideBtT bg-red-200">

    </div> -->





{% endblock %}