BellzStudio/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from BellzStudio import settings

from django.conf.urls.static import static # type: ignore

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("dev-stories/", include('stories.urls')),
    path("notes/", include('notes.urls')),

    # ---- API ROUTES ----
    path("api/accounts/", include('main.apiUrls')),
    path("api/notes/", include('notes.apiUrls')),

    
] + static(settings.STATIC_URL)
# + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

main/urls.py
from django.urls import path
from .views import *


app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path("about-us/", about, name="about-us"),
    path("contact/", contact, name="contact"),
    path("contact/<str:destination>/", contactType, name="contact_type"),


    # ----------- USER MANGEMENT   -------------
    path("profile/me", profile, name="profile"),
    path("profile/update", updateProfile, name="update-profile"),

    # ----------- USER AUTHENTICATION   -------------
    path("get-familiar", signUp, name="sign-up"),
    path("sign-in", signIn, name="sign-in"),
    path("sign-out", signOut, name="sign-out"),


    
    
]

notes/urls.py
from django.urls import path

from .api_v1_views import ApiV1Home



app_name = "notes"

urlpatterns = [
    # path("", index, name="index"),
    # path("write/", NewNote, name="write-note"),
    # # path("<uuid:noteID>/", Note, name="note"),
    # path("<str:date>/", NoteDate, name="notes-by-date"),
    # path("idea-tags/<uuid:id>/", IdeaNotes, name="notes-by-idea"),
    # path("new-idea/", NewIdea, name="new-idea"),
    # path("search/", Search, name="search"),
    # path("note/<str:slug>/", NoteView, name="note"),
    # path("d/<str:date>/", NoteDate, name="notes-by-date"),
    # path("idea-tags/<str:slug>/", IdeaNotes, name="notes-by-idea"),


    # # ----------- NOTE REACH    -------------
    # path("n/join-network/", networks, name="join-network"),
    # path("n/subscribe/", subscribe, name="subscribe"),
    # path("network/<int:level>/", network, name="network"),
    
    # ------ v1.API  ------
    path("v1", ApiV1Home.as_view(), name="api_home"),

]

notes/models.py
from django.db import models
import uuid
from django.utils.text import slugify

from main.models import User 
# Create your models here.


class IdeaTag(models.Model):
    slug = models.SlugField(max_length=40, primary_key=True, unique=True, blank=True)
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.name[0] != "#":
            self.name = f"#{self.name}"

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    

    def my_notes(self):
        return self.on_notes.all()

class NotePrivacy(models.Model):
    name = models.CharField(max_length=150, unique=True)
    level = models.IntegerField(unique=True)


    # ---- Network Info ----
    # color_code = models.CharField(max_length=20, null=True)


    class Meta:
        ordering = ('level',)

    def get_subscribers(self):
        try: 
            subs = Note.objects.filter(privacy_level=self)
            print(subs)
            print(self)
        except Exception as e:
            print(e)
            raise e
        
        return subs

    def __str__(self):
        return f"{self.level}: {self.name}"

class Note(models.Model):
    slug = models.SlugField(max_length=160, primary_key=True, unique=True, blank=True)
    title = models.CharField(max_length=150)
    text = models.TextField(null=False, blank=False)
    tags = models.ManyToManyField(IdeaTag, related_name='on_notes')
    privacy_level = models.ForeignKey(NotePrivacy, on_delete=models.SET_NULL, null=True, related_name="subGroup")
    written_at = models.DateTimeField(auto_now_add=True)


    

    class Meta: 
        ordering = ('-written_at', ) 

    def __str__(self): 
        return self.title 
    
def get_default_subscription_model():
    return NotePrivacy.objects.get(level='5').id

class Reader(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=False, related_name='reader_profile')

    subscription_level = models.ForeignKey(NotePrivacy, on_delete=models.SET_NULL, null=True, default=get_default_subscription_model )
    
    written_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    
    
    default =  {
        'id': "test-uuid",
        'user': {
                "id": "test-user-id-1",
                "email": "test-user-1"
        },
        'subscription_level': "test-uuid",
        'written-at': "test-uuid",
        'updated_at': "test-uuid",
        
    }

    class Meta: 
        ordering = ('-updated_at', ) 

    def __str__(self): 
        if self.user:
            return f"{self.user.email}" 
        else:
            return f"{self.default['user']['email']}" 

notes/forms.py
from django.forms import ModelForm

from .models import Note


class NoteForm(ModelForm):

    class Meta:
        model = Note
        fields = "__all__"

notes/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from datetime import timedelta, datetime
from datetime import date as realDate
import time
from django.urls import reverse
from requests import Response
from notes.serializers import IdeaTagSerializer
from notes.paginations import StandardResultsSetPagination
from notes.serializers import NoteSerializer
from django.contrib.auth.decorators import login_required
from notes.forms import NoteForm
from .models import Note, IdeaTag, NotePrivacy, Reader
# Create your views here.

from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer



def index(request):
    errors = {}
    print("Request user : ", request.user)
    user= request.user

    if not user.is_authenticated:
        user_first = ''
    else:
        if len(user.first_name) > 1:
            user_first = user.first_name[0]
        else:
            user_first = f"{user}"[0]
    # Date Selector
    week = []
    d = realDate.today()
    for x in range(-3, 4):
        week.append(d + timedelta(days=x))
    # Tags
    tags = IdeaTag.objects.all()
    try:
        tag_param = request.GET['tag']
        # print("Tag Param: ", request.GET['tag'])
    except Exception as e:
        tag_param = None
        # print("Error: ", e)
    
    if tag_param:
        try:
            tag_param = f"#{tag_param}"
            tag_param = IdeaTag.objects.get(name=tag_param)
        except Exception as e:
            print("No tag: ", e)
            tag_param = None
    
    
    # Fetch notes based n user's network
    # If request user is autheicted
    if not request.user.is_authenticated:
        notes = Note.objects.filter(privacy_level__level__gte=5)
        return render(request, 'notes/all-notes.html', {'week': week, 'notes': notes, 'tags': tags, 'errors': errors})


    # Get auth'd user reader profile
    try:
        reader_profile = Reader.objects.get(user=request.user)
    except Exception as e:
        # Couldn't get reader profile
        print(e)
        reader_profile = None
    if reader_profile == None:
        print(f"{request.user} is auth bu no reader profile assuming the" )
        if request.user.is_staff:
            notes = Note.objects.all()
        
    else:
        reader = reader_profile
        print("This Reader: ", reader)
        
        subscription = reader.subscription_level
        print("Subscription: ", subscription)
        print("Leve: ", subscription.level, "ID", subscription.id)

        notes = Note.objects.filter(privacy_level__level__gte=subscription.level)
        


    print("Notes: ", notes)

    print("Result length: ", len(notes))
    #errors['invalid_idea_format'] = "Invalid idea format"


class Notes(generics.RetrieveAPIView):
    """
    A view that returns a templated HTML representation of a given user.
    """
    queryset = Note.objects.all()
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, *args, **kwargs):
                # Date Selector
        week = []
        d = realDate.today()
        for x in range(-3, 4):
            week.append(d + timedelta(days=x))

        tags = IdeaTag.objects.all()
        posts = Note.objects.all()

        return Response({'week': week, 'notes': posts, 'tags': tags}, template_name='notes/all-notes.html')

    # return render(request, 'notes/all-notes.html', {'week': week, "user_first": user_first, 'notes': notes, 'tags': tags, 'errors': errors})

def NewNote(request):
    '''
    On GET: This view returns the entry form page on get
    On POST: calls the validate_entry(entry), if valid, calls parse_entry(entry) then save entry.

    '''
    if request.method == "POST":
        # Get authenticated user
        user = request.user


        # Get submited entry text
        print("Form: ", request.POST)
        d = dict(request.POST)
        print("Dict form: ", d)
        title = d['title'][0].title()
        print("Title: ", title)
        text = d['text'][0]
        print("Text: ", text)
        tags = d['tags']
        print("Tags: ", tags)
        privacy_level = d['privacy_level'][0]   # int(d['privacy_level'][0])+1
        print("Privacy Level: ", privacy_level)


        # # # Create new note instance
        try:
            pl = NotePrivacy.objects.get(level=privacy_level)
            new_note = Note.objects.create(title=title, text=text, privacy_level=pl)
            new_note.tags.set(tags)

        except Exception as e:
            print("Error: ", e)
            return HttpResponseRedirect(reverse("notes:index"))

        # # # Save new entry instance
        # new_note.save()

        # Redirect back home
        return HttpResponseRedirect(reverse("notes:index"))
    
    write_form_note = NoteForm()
    return render(request, 'notes/write.html', {'form': write_form_note})

def NewIdea(request):
    if request.method == "POST":

        idea_name = request.POST['idea_name']
        errors ={}
        errors['invalid_idea_format'] = "Invalid idea format"
        if len(idea_name) < 2:
            return HttpResponseRedirect(reverse("notes:index", 
                                                args=(), kwargs=()
                                        ))
        try:
            IdeaTag.objects.get_or_create(name=idea_name)
        except Exception as e:
            return HttpResponse("Error creating tag")


        return HttpResponseRedirect(reverse("notes:index"))

def NoteDate(request, date):
    print("Date: ", date)
    try:
        tag_param = request.GET['tag']
        print("Tag Param: ", request.GET['tag'])
    except Exception as e:
        tag = None
        print("Error: ", e)


    # Date Selector  content_params path
    week = []
    d = realDate.today()
    for x in range(-3, 4):
        week.append(d + timedelta(days=x))

    notes = Note.objects.filter(written_at__date=date)   
    notes_tags = list()
    # notes_tags = set(notes_tags)
    # notes_tags = list(notes_tags)

    if tag == None:
        for x in notes:
            for i in x.tags.values():
                notes_tags.append({
                                'id': dict(i)['id'],
                                'name': dict(i)['name']
                            })

    return render(request, 'notes/notes-date.html', 
                  {
                    'week': week, 
                    "day_notes": notes,
                    "tags": notes_tags
                })

def IdeaNotes(request, slug):
    try:
        idea = IdeaTag.objects.get(slug=slug)
    except:
        idea = IdeaTag.objects.none()
    

    # Get auth'd user reader profile
    try:
        reader_profile = Reader.objects.get(user=request.user)
    except Exception as e:
        # Couldn't get reader profile
        print(e)
        reader_profile = None
    if reader_profile == None:
        print(f"{request.user} is has no reader profile " )
        if request.user.is_staff:
            notes = Note.objects.all()
        else:
            idea_notes = idea.my_notes()
            notes = idea_notes.filter(privacy_level__level__gte=5)    
    else:
        reader = reader_profile
        print("This Reader: ", reader)
        
        subscription = reader.subscription_level
        print("Subscription: ", subscription)
        print("Level: ", subscription.level, "ID", subscription.id)
        idea_notes = idea.my_notes()
        notes = idea_notes.filter(privacy_level__level__gte=subscription.level )

    
    count = idea.my_notes().count()
    return render(request, 'notes/idea-notes.html', {'idea': idea, 'idea_notes': notes, 'idea_notes_count': count})

def NoteView(request, slug):
    try:
        note = Note.objects.get(slug=slug)
    except:
        note = None
    
    return render(request, "notes/note.html", {"note": note})

def Search(request):
    query = request.GET['query'].lower()
    print("Search Query: ", query)
    note_results = []
    notes = Note.objects.all()
    for note in notes:
        if query.lower() in note.text.lower():
            note_results.append(note)

    print(note_results)

    idea_results = []
    ideas = IdeaTag.objects.all()
    for idea in ideas:
        if query.lower() in idea.name.lower():
            idea_results.append(idea)

    print(idea_results)

    note_result_pks = [n.pk for n in note_results]

    note_results = Note.objects.filter(pk__in=note_result_pks) 

    # Get auth'd user reader profile
    try:
        reader_profile = Reader.objects.get(user=request.user)
    except Exception as e:
        # Couldn't get reader profile
        print(e)
        reader_profile = None
    if reader_profile == None:
        print(f"{request.user} is has no reader profile " )
        if request.user.is_staff:
            pass
        else:
            note_results = note_results.filter(privacy_level__level__gte=5)    
    else:
        reader = reader_profile
        print("This Reader: ", reader)
        
        subscription = reader.subscription_level
        print("Subscription: ", subscription)
        print("Level: ", subscription.level, "ID", subscription.id)
        note_results = note_results.filter(privacy_level__level__gte=subscription.level )
        
    return render(request, "notes/search.html", {

        "note_results": note_results,
        "idea_results": idea_results,
        "results_length": len(note_results) + len(idea_results)

        })

#    API ---------
class ApiV1Home(generics.ListAPIView):
    queryset = Note.objects.all().order_by("written_at")
    serializer_class = NoteSerializer
    permission_classes = []
    pagination_class = StandardResultsSetPagination
    search_fields = ['title']



def networks(request):

    networks = NotePrivacy.objects.all()
    
    return render(request, "notes/monitize/join-network.html", {"networks": networks})

def network(request, level):
    networks = NotePrivacy.objects.all()
    try:
        network = NotePrivacy.objects.get(level=level)

notes/templates/notes/monitize/join-network.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
        <title> BellzStudio </title>
    </head>

    <body class="relative w-full h-full">
        
        <div class="bg-slate-50 border text-gray-800  w-full md:h-screen   flex flex-col md:space-x-4 lg:space-x-8 md:flex-row md:justify-between md:items-center px-2 md:px-10 lg:px-20 space-y-2 md:space-y-0 ">
            
            <div class="w-full space-y-2 md:space-y-0  md:flex p-4 mt-8 md:mt-0 gap-2 md:gap-4 items-center rounded-md shadow shadow-lg">
                
                {% for ntw in networks %}
                <div class="shadow border p-2 rounded-md flex flex-col w-full justify-between items-center">
                    <h1 
                        class="font-bold text-gray-700 "
                        >
                        
                            
                            <a href="{% url 'notes:network' ntw.level %} " class="font-medium bg-white border   rounded py-1 cursor-pointer px-2"> {{ntw.name}} </a> 
                        
                    </h1>

                    <span class="">
                        <p class="text-balance"> This means you will have access to read all my note marked <span class="italic font-medium">{{network.name}} </span></p>
                        <p class="text-balance"> By extension, you can also read notes with privacy levels to the this level</span></p>
                    </span>
                    
                    <form class="text-gray-800" action="{% url 'notes:subscribe' %}" method="POST">
                        {% csrf_token %}
                        
                        <input type="text" name="network_level" value="{{ntw.level}}" class="hidden">
                        
                        
                        <input type="submit" class="w-full  hover:bg-purple-700 bg-purple-600 p-1 text-white cursor-pointer rounded" value="Send request">
                    </form>
                </div>
                {% endfor %} 
                

            </div>    
            
            
        </div>
        <img src="{% static 'images/curlyVectorTop.svg' %}" alt="curlyV" class="absolute top-0 left-0 "/>
        <img src="{% static 'images/curlyVectorBottom.svg' %}" alt="curlV" class=" absolute  -bottom-16 md:-bottom-1 right-0 "/>
        <a href="/" class="absolute  top-2 left-2 text-white text-sm space-x-2 flex items-center "> 
            <img src="{% static 'images/arrow-circle-left-white.svg' %}" alt="go back" class="w-7 h-7 text-white hover:animate-swivvle" >
            <p> Go home </p>
        </a>
    </body>

</html>

notes/templates/notes/monitize/network.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/output.css' %}">
        <title> BellzStudio </title>
    </head>

    <body class="relative w-full h-full">
        
        <div class="bg-slate-50 text-gray-800  w-full md:h-screen   flex flex-col md:space-x-4 lg:space-x-8 md:flex-row md:justify-between md:items-center px-2 md:px-20 lg:px-40 space-y-2 md:space-y-0 ">
            
            <div class="w-full  p-4 md:w-1/2 mt-8 md:mt-0 space-y-3">
                <div class="">
                    <h1 
                        class="font-bold text-gray-700 text-xl md:text-3xl"
                        >
                        {% if user.is_authenticated %}
                            Hi <span class="text-purple-700 "> {{user.first_name}} </span>! You are a member of my 
                        {% else %}
                            Hi there! Become a member of my 
                        {% endif %} 
                    </h1>
                    <h2 class="font-extrabold text-purple-600 text-7xl py-2">
                        <p class="w-full text-start ">{{network.name}} </p> 
                    </h1>
                </div>
                
                <div class="py-2">
                    <p class=""> This means you will have access to read all my note marked <span class="italic font-medium">{{network.name}} </span></p>
                    <p class=""> By extension, you can also read notes with privacy levels to the this level</span></p>
                </div>

                {% if user.is_authenticated %}
                     
                    {% if network.level < user.reader_profile.subscription_level.level   %}
                        <form class="text-gray-800" action="{% url 'notes:subscribe' %}" method="POST">
                            {% csrf_token %}
                            
                            <input type="text" name="network_level" value="{{network.level}}" class="hidden">
                            
                            
                            <input type="submit" class="w-full  hover:bg-purple-700 bg-purple-600 p-1 text-white cursor-pointer rounded" value="Send request to join">
                        </form>
                    {% endif %}

                    {% else %}
                        <span class="space-x-2">
                            <a href="{% url 'main:sign-up' %}" class="mt-10 underline text-purple-700 font-medium"> Get familiar </a>
                            <a href="{% url 'main:sign-in' %}" class="mt-10 underline text-purple-700 font-medium"> Sign In </a>
                        </span>
                {% endif %}
                
                
            </div>    
            
            <div class="w-full h-full justify-center items-center  aimate-slideBtT md:aimate-[slideRtL_1.5s_ease-in-out]  md:w-1/2 md:mb-0 flex justify-center">

                    <!-- 
                        w-full min-h-[150px]  md:h-1/2 gap-2 justify-center  flex  rounded-md
                            {% for ntw in networks %}
                    <a 
                        href="{% url 'notes:network' ntw.level %}" > 
                        <div class="text-5xl border w-full min-w-[50px] rounded font-bold w-full flex flex-col justify-between hover:bg-purple-100 justify-center h-full">


                                {% if network.name == ntw.name %}
                                    <p class="text-purple-600 text-xs p-2">{{ntw.name}} </p>
                                {% else %}
                                    <p class="text-gray-900 text-xs p-2">{{ntw.name}} </p>
                                {% endif %}
                            <p class="text-gray-900 text-xs p-2"> {{ntw.get_subscribers.count}} </p>
                            <p class="text-gray-900 text-xs p-2"> {{ntw.level}} </p>
                        </div>
                    </a>

                    {% endfor%} -->
                    <div class="w-11/12 border border-purple-100 rounded">
                        <div class="z-400  border w-full min-w-[50px] rounded w-full flex flex-col justify-between hover:shadow justify-center h-full">
                            
                            <p class="text-gray-800 text-xs p-2 font-bold"> {{network.name}}  </p>
                            <img src="" class="h-60 w-full bg-purple-600">
                            <span class="w-full grid animate-fadeIn delay-2000 py-2 grid-cols-custom-5 justify-center items-center">
                                {% for i in  networks %}
                                <div class="flex flex-col justify-center items-center">
                                    <a 
                                    href="{% url 'notes:network' i.level %}" 
                                    class=" {% if network.name == i.name %} text-purple-600 border-purple-600 {% else %} animate-fadeIn text-gray-900 {% endif %}  text-xs w-12 h-12 border-2 rounded-full flex justify-center items-center p-2"> {{i.level}}</a>
                                    <!-- <p class="text-xs"> {{i.level}} </p> -->
                                </div>
                                {% endfor %}
                            </span>
                            <p class="text-gray-900 w-full justify-center flex  text-xs "> {{network.get_subscribers.count}} subscribers </p>

                            
                            <p class="text-gray-900 w-full justify-end flex text-xs p-2"> Level {{network.level}} of {{networks.count}} </p>
                             
                            
                    </div>
                    </div>
            
                
                
            </div>
            
            
        </div>
        <img src="{% static 'images/curlyVectorTop.svg' %}" alt="curlyV" class="absolute top-0 left-0 "/>
        <img src="{% static 'images/curlyVectorBottom.svg' %}" alt="curlV" class=" absolute  -bottom-16 md:-bottom-1 right-0 "/>
        <a href="/" class="absolute  top-2 left-2 text-white text-sm space-x-2 flex items-center "> 
            <img src="{% static 'images/arrow-circle-left-white.svg' %}" alt="go back" class="w-7 h-7 text-white hover:animate-swivvle" >
            <p> Go home </p>
        </a>
    </body>

</html>